### ISSUE TITLE
Navbar items are displayed badly

### ISSUE THREAD

**Issue by im-n1** [elenatorro/allineed#1]
Since I live minimalism I love your work. Well done mate, keep up ;)

I've found small issue on the web.

![selection_010](https://cloud.githubusercontent.com/assets/198654/17276057/55152f64-571d-11e6-87dc-0abc4dbc8847.png)

**Comment by elenatorro** [comment]
You mean the second navbar is too large, and the 'blockquotes' item looks weird, right? What do you suggest? 

Thanks :) 👍

**Comment by im-n1** [comment]
Yes, exactly.

1 option: shring the margin between menu item.
2 option: shrink "blockquotes" to "b-quotes".

**Comment by elenatorro** [comment]
Just fixed it! This is the [commit](https://github.com/elenatorro/allineed/commit/b9fd2a8508c4c99ea4e80d3d8c55b5927cbe33f8)

![screen shot 2016-07-31 at 14 40 04](https://cloud.githubusercontent.com/assets/3824953/17276508/007a969c-572c-11e6-9b81-9ed90bf54ed2.png)

Thank you very much for the feedback!
